disabled_rules:
#  - trailing_whitespace
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - file_length
  - for_where
